linke_hand = 0

def on_button_a():
    global linke_hand
    linke_hand = 1
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.QUARTER))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
input.on_button_event(Button.A, input.button_event_click(), on_button_a)

def on_button_ab():
    basic.show_icon(IconNames.HAPPY)
    basic.pause(1000)
    basic.show_icon(IconNames.SAD)
    basic.clear_screen()
    for index in range(3):
        basic.set_led_color(0xff0000)
        basic.pause(1000)
        basic.turn_rgb_led_off()
        basic.pause(100)
    for index2 in range(3):
        basic.set_led_color(0xff0000)
        basic.pause(500)
        basic.turn_rgb_led_off()
        basic.pause(100)
input.on_button_event(Button.AB, input.button_event_click(), on_button_ab)

def on_button_b():
    for index3 in range(10):
        basic.set_led_color(0xff0000)
        basic.pause(100)
        basic.set_led_color(0xff8000)
        basic.pause(100)
        basic.set_led_color(0xffff00)
        basic.pause(100)
        basic.set_led_color(0xff9da5)
        basic.pause(100)
        basic.set_led_color(0x00ff00)
        basic.pause(100)
        basic.set_led_color(0xb09eff)
        basic.pause(100)
        basic.set_led_color(0x0000ff)
        basic.pause(100)
        basic.turn_rgb_led_off()
input.on_button_event(Button.B, input.button_event_click(), on_button_b)

def on_forever():
    if linke_hand > 0:
        for index4 in range(5):
            basic.set_led_color(0xff0000)
            basic.pause(100)
            basic.set_led_color(0xff8000)
            basic.pause(100)
            basic.set_led_color(0xffff00)
            basic.pause(100)
            basic.set_led_color(0xff9da5)
            basic.pause(100)
            basic.set_led_color(0x00ff00)
            basic.pause(100)
            basic.set_led_color(0xb09eff)
            basic.pause(100)
            basic.set_led_color(0x00ffff)
            basic.pause(100)
            basic.set_led_color(0x007fff)
            basic.pause(100)
            basic.set_led_color(0x65471f)
            basic.pause(100)
            basic.set_led_color(0x0000ff)
            basic.pause(100)
            basic.set_led_color(0x7f00ff)
            basic.pause(100)
            basic.set_led_color(0xff0080)
            basic.pause(100)
            basic.set_led_color(0xff00ff)
            basic.pause(100)
            basic.set_led_color(0xffffff)
            basic.pause(100)
            basic.set_led_color(0x999999)
            basic.pause(100)
            basic.set_led_color(0x000000)
            basic.turn_rgb_led_off()
basic.forever(on_forever)

def on_forever2():
    global linke_hand
    if linke_hand > 0:
        linke_hand = 0
        basic.show_string("Nerver gonna give you up", 65)
basic.forever(on_forever2)
